# Generated by Django 3.0.8 on 2020-07-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djcelery_model', '0002_auto_20190125_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltaskmeta',
            name='task_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='modeltaskmeta',
            unique_together={('content_type', 'object_id', 'task_id')},
        ),
    ]
